apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: mongo-express
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: mongo-express
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50